import { useState } from "react";
import React from 'react';
import { ethers, BigNumber } from 'ethers';
import durlabhNFTs from '../artifacts/contracts/DurlabhNFTs.sol/DurlabhNFTs.json';

const durlabhNFTsAddress = '0x0872BA9783B57eD1959489d6dCb01d7b314260eb';

function MainMint({ accounts, setAccounts }) {
    const [mintAmount, setMintAmount] = useState(1); 
    const isConnected = Boolean(accounts[0]);

    async function handleMint() {
        if(window.ethereum) {
            const provider = new ethers.providers.Web3Provider(window.ethereum);
            const signer = provider.getSigner();
            const contract = new ethers.Contract(
                durlabhNFTsAddress,
                durlabhNFTs.abi,
                signer
            );
            try {
                const response = contract.mintMe(BigNumber.from(mintAmount));
                console.log('Contract response to mint:', response);
            } catch (error) {
                console.log('Error encountered:', error);
            }
        }
    }

    function handleDecrement() {
        if(mintAmount <= 1) return;
        setMintAmount(mintAmount - 1);
    }

    function handleIncrement() {
        if(mintAmount >= 3) return;
        setMintAmount(mintAmount + 1);
    }

  return (
    <main>
        <h1>Durlabh NFTs</h1>
        <p>NFTs which are one of a kind. Images generated by AI which haven't been generated before and will never be generated again. Each NFT represents a unique state of being as imagined by AI. Only one like this exists, and can never exist again.</p>
        {isConnected ? (
            <section>
                <div>
                    <button onClick={handleDecrement}>-</button>
                    <input type="number" value={mintAmount} />
                    <button onClick={handleIncrement}>+</button>
                </div>
                <button onClick={handleMint}>Mint now!</button>
            </section>
        ) : (
            <p>You must be connected to mint</p>
        )}
    </main>
  )
}

export default MainMint